import React, {useState} from 'react';
import '../styles/BestDealFinder.css';

const BestDealFinder = () => {
  const dealsByCategory = {
    Shopping: [
      {
        id: '1',
        item: 'Sony Wireless Headphones',
        platform: 'Amazon',
        dealPrice: 2999,
        originalPrice: 4999,
        rating: 4.5,
        validTill: '2025-06-10',
        url: 'https://www.amazon.in/dp/B09XX1XX1X',
      },
      {
        id: '2',
        item: 'Myntra Flat 60% Off on Fashion',
        platform: 'Myntra',
        dealPrice: 999,
        originalPrice: 2499,
        rating: 4.3,
        validTill: '2025-06-11',
        url: 'https://www.myntra.com/',
      },
      {
        id: '13',
        item: 'Flipkart Electronics Sale',
        platform: 'Flipkart',
        dealPrice: 4999,
        originalPrice: 8999,
        rating: 4.6,
        validTill: '2025-06-15',
        url: 'https://www.flipkart.com/',
      },
      {
        id: '4',
        item: 'Meesho Fashion Fest',
        platform: 'Meesho',
        dealPrice: 799,
        originalPrice: 1599,
        rating: 4.1,
        validTill: '2025-06-18',
        url: 'https://meesho.com/',
      },
      {
        id: '5',
        item: 'JBL Bluetooth Speaker Deal',
        platform: 'Amazon',
        dealPrice: 3499,
        originalPrice: 5499,
        rating: 4.6,
        validTill: '2025-06-22',
        url: 'https://www.amazon.in/',
      },
      {
        id: '6',
        item: 'Ajio Buy 1 Get 1 Offer',
        platform: 'Ajio',
        dealPrice: 1200,
        originalPrice: 2400,
        rating: 4.2,
        validTill: '2025-06-25',
        url: 'https://www.ajio.com/',
      },
      {
        id: '7',
        item: 'Snapdeal Summer Sale',
        platform: 'Snapdeal',
        dealPrice: 850,
        originalPrice: 1700,
        rating: 4.0,
        validTill: '2025-07-05',
        url: 'https://www.snapdeal.com/',
      },
      {
        id: '8',
        item: 'Amazon Fashion Fest',
        platform: 'Amazon',
        dealPrice: 1500,
        originalPrice: 3000,
        rating: 4.4,
        validTill: '2025-07-20',
        url: 'https://www.amazon.in/fashion',
      },
      {
        id: '9',
        item: 'Flipkart Big Billion Days Preview',
        platform: 'Flipkart',
        dealPrice: 2999,
        originalPrice: 5999,
        rating: 4.5,
        validTill: '2025-08-10',
        url: 'https://www.flipkart.com/big-billion-days',
      },
      {
        id: '10',
        item: 'Tata CLiQ Luxury Sale',
        platform: 'Tata CLiQ',
        dealPrice: 4999,
        originalPrice: 9999,
        rating: 4.3,
        validTill: '2025-09-01',
        url: 'https://www.tatacliq.com/',
      },
      {
        id: '41',
        item: 'Croma Mobile Accessories Sale',
        platform: 'Croma',
        dealPrice: 1299,
        originalPrice: 2399,
        rating: 4.2,
        validTill: '2025-07-15',
        url: 'https://www.croma.com/',
      },
      {
        id: '42',
        item: 'Lenskart Eyewear Offers',
        platform: 'Lenskart',
        dealPrice: 1599,
        originalPrice: 3199,
        rating: 4.4,
        validTill: '2025-07-18',
        url: 'https://www.lenskart.com/',
      },
      {
        id: '43',
        item: 'Tata CLiQ Electronics Sale',
        platform: 'Tata CLiQ',
        dealPrice: 3999,
        originalPrice: 6999,
        rating: 4.5,
        validTill: '2025-07-20',
        url: 'https://www.tatacliq.com/',
      },
      {
        id: '44',
        item: 'Myntra Kids Fashion Sale',
        platform: 'Myntra',
        dealPrice: 799,
        originalPrice: 1799,
        rating: 4.3,
        validTill: '2025-08-05',
        url: 'https://www.myntra.com/kids',
      },
      {
        id: '45',
        item: 'Amazon Home Essentials Discount',
        platform: 'Amazon',
        dealPrice: 1299,
        originalPrice: 2499,
        rating: 4.1,
        validTill: '2025-08-10',
        url: 'https://www.amazon.in/home-essentials',
      },
      {
        id: '46',
        item: 'Flipkart Furniture Fest',
        platform: 'Flipkart',
        dealPrice: 5499,
        originalPrice: 10999,
        rating: 4.6,
        validTill: '2025-08-15',
        url: 'https://www.flipkart.com/furniture',
      },
      {
        id: '47',
        item: 'Meesho Handicraft Sale',
        platform: 'Meesho',
        dealPrice: 699,
        originalPrice: 1399,
        rating: 4.2,
        validTill: '2025-08-20',
        url: 'https://meesho.com/handicrafts',
      },
      {
        id: '48',
        item: 'Ajio Winter Collection Discount',
        platform: 'Ajio',
        dealPrice: 899,
        originalPrice: 1799,
        rating: 4.0,
        validTill: '2025-08-25',
        url: 'https://www.ajio.com/winter',
      },
      {
        id: '49',
        item: 'Snapdeal Electronics Fest',
        platform: 'Snapdeal',
        dealPrice: 1999,
        originalPrice: 3999,
        rating: 4.3,
        validTill: '2025-09-05',
        url: 'https://www.snapdeal.com/electronics',
      },
      {
        id: '50',
        item: 'Amazon Smart Home Devices Sale',
        platform: 'Amazon',
        dealPrice: 3999,
        originalPrice: 6999,
        rating: 4.5,
        validTill: '2025-09-10',
        url: 'https://www.amazon.in/smarthome',
      },
    ],

    Food: [
      {
        id: '11',
        item: "50% off on Domino's Pizza",
        platform: 'Dominos',
        dealPrice: 199,
        originalPrice: 399,
        rating: 4.2,
        validTill: '2025-06-08',
        url: 'https://www.dominos.co.in/',
      },
      {
        id: '12',
        item: 'Swiggy ₹100 Off on 1st Order',
        platform: 'Swiggy',
        dealPrice: 150,
        originalPrice: 250,
        rating: 4.4,
        validTill: '2025-06-13',
        url: 'https://www.swiggy.com/',
      },
      {
        id: '3',
        item: 'FoodPanda Lunch Deal',
        platform: 'FoodPanda',
        dealPrice: 120,
        originalPrice: 250,
        rating: 4.0,
        validTill: '2025-06-10',
        url: 'https://www.foodpanda.in/',
      },
      {
        id: '14',
        item: 'Zomato Gold 20% Cashback',
        platform: 'Zomato',
        dealPrice: 0,
        originalPrice: 0,
        rating: 4.3,
        validTill: '2025-06-20',
        url: 'https://www.zomato.com/',
      },
      {
        id: '15',
        item: 'McDonald’s Combo Meal at ₹99',
        platform: 'McDelivery',
        dealPrice: 99,
        originalPrice: 199,
        rating: 4.5,
        validTill: '2025-06-26',
        url: 'https://www.mcdelivery.co.in/',
      },
      {
        id: '16',
        item: 'Pizza Hut ₹150 Cashback',
        platform: 'Pizza Hut',
        dealPrice: 250,
        originalPrice: 400,
        rating: 4.1,
        validTill: '2025-06-24',
        url: 'https://www.pizzahut.co.in/',
      },
      {
        id: '17',
        item: 'Burger King Summer Deals',
        platform: 'Burger King',
        dealPrice: 199,
        originalPrice: 350,
        rating: 4.2,
        validTill: '2025-07-15',
        url: 'https://www.burgerking.in/',
      },
      {
        id: '18',
        item: 'KFC Family Bucket Offer',
        platform: 'KFC',
        dealPrice: 499,
        originalPrice: 849,
        rating: 4.3,
        validTill: '2025-07-18',
        url: 'https://www.kfc.co.in/',
      },
      {
        id: '19',
        item: 'Domino’s Buy 1 Get 1 Free',
        platform: 'Dominos',
        dealPrice: 299,
        originalPrice: 598,
        rating: 4.4,
        validTill: '2025-07-25',
        url: 'https://www.dominos.co.in/',
      },
      {
        id: '20',
        item: 'Zomato Pro Weekend Deals',
        platform: 'Zomato',
        dealPrice: 0,
        originalPrice: 0,
        rating: 4.5,
        validTill: '2025-08-01',
        url: 'https://www.zomato.com/',
      },
      {
        id: '51',
        item: 'Swiggy Super Saver Meal',
        platform: 'Swiggy',
        dealPrice: 129,
        originalPrice: 229,
        rating: 4.3,
        validTill: '2025-07-28',
        url: 'https://www.swiggy.com/',
      },
      {
        id: '52',
        item: 'Zomato Flat ₹200 Off on Dinner Orders',
        platform: 'Zomato',
        dealPrice: 299,
        originalPrice: 499,
        rating: 4.6,
        validTill: '2025-07-20',
        url: 'https://www.zomato.com/',
      },
      {
        id: '53',
        item: 'FoodPanda Evening Snacks Combo',
        platform: 'FoodPanda',
        dealPrice: 99,
        originalPrice: 199,
        rating: 4.1,
        validTill: '2025-07-10',
        url: 'https://www.foodpanda.in/',
      },
      {
        id: '54',
        item: "McDonald's Weekend Special – 2 Burgers + Fries",
        platform: 'McDelivery',
        dealPrice: 149,
        originalPrice: 299,
        rating: 4.4,
        validTill: '2025-07-30',
        url: 'https://www.mcdelivery.co.in/',
      },
      {
        id: '75',
        item: 'KFC Chicken Popcorn Large at ₹149',
        platform: 'KFC',
        dealPrice: 149,
        originalPrice: 269,
        rating: 4.2,
        validTill: '2025-08-05',
        url: 'https://www.kfc.co.in/',
      },
      {
        id: '56',
        item: 'Domino’s Weekday Treat - 40% Off on Medium Pizza',
        platform: 'Dominos',
        dealPrice: 180,
        originalPrice: 300,
        rating: 4.3,
        validTill: '2025-07-17',
        url: 'https://www.dominos.co.in/',
      },
      {
        id: '57',
        item: 'Burger King Royale Chicken Combo',
        platform: 'Burger King',
        dealPrice: 179,
        originalPrice: 299,
        rating: 4.0,
        validTill: '2025-07-22',
        url: 'https://www.burgerking.in/',
      },
      {
        id: '58',
        item: 'Pizza Hut Medium Pan Pizza at ₹199',
        platform: 'Pizza Hut',
        dealPrice: 199,
        originalPrice: 350,
        rating: 4.3,
        validTill: '2025-07-25',
        url: 'https://www.pizzahut.co.in/',
      },
      {
        id: '59',
        item: 'Zomato Pro Plus – Free Delivery for 1 Month',
        platform: 'Zomato',
        dealPrice: 0,
        originalPrice: 0,
        rating: 4.6,
        validTill: '2025-08-15',
        url: 'https://www.zomato.com/',
      },
      {
        id: '60',
        item: 'Swiggy Biryani Festival – Flat ₹120 Off',
        platform: 'Swiggy',
        dealPrice: 180,
        originalPrice: 300,
        rating: 4.5,
        validTill: '2025-07-19',
        url: 'https://www.swiggy.com/',
      },
    ],
    Travel: [
      {
        id: '21',
        item: 'Uber ₹50 Off on 3 Rides',
        platform: 'Uber',
        dealPrice: 150,
        originalPrice: 300,
        rating: 4.3,
        validTill: '2025-06-12',
        url: 'https://www.uber.com/in/en/',
      },
      {
        id: '22',
        item: 'Ola ₹75 Cashback on Payments',
        platform: 'Ola',
        dealPrice: 225,
        originalPrice: 300,
        rating: 4.1,
        validTill: '2025-06-09',
        url: 'https://www.olacabs.com/',
      },
      {
        id: '23',
        item: 'Rapido ₹30 Off Promo',
        platform: 'Rapido',
        dealPrice: 70,
        originalPrice: 100,
        rating: 4.0,
        validTill: '2025-06-10',
        url: 'https://www.rapido.bike/',
      },
      {
        id: '24',
        item: 'Uber Pass 20% Off',
        platform: 'Uber',
        dealPrice: 159,
        originalPrice: 199,
        rating: 4.5,
        validTill: '2025-06-30',
        url: 'https://www.uber.com/in/en/',
      },
      {
        id: '25',
        item: 'RedBus ₹100 Discount',
        platform: 'RedBus',
        dealPrice: 400,
        originalPrice: 500,
        rating: 4.3,
        validTill: '2025-06-22',
        url: 'https://www.redbus.in/',
      },
      {
        id: '26',
        item: 'Makemytrip Flight Coupons',
        platform: 'MakeMyTrip',
        dealPrice: 4800,
        originalPrice: 5200,
        rating: 4.2,
        validTill: '2025-06-28',
        url: 'https://www.makemytrip.com/',
      },
      {
        id: '27',
        item: 'Goibibo ₹300 Off on Hotels',
        platform: 'Goibibo',
        dealPrice: 2700,
        originalPrice: 3000,
        rating: 4.0,
        validTill: '2025-07-10',
        url: 'https://www.goibibo.com/',
      },
      {
        id: '28',
        item: 'IRCTC ₹50 Cashback on Train Tickets',
        platform: 'IRCTC',
        dealPrice: 450,
        originalPrice: 500,
        rating: 4.2,
        validTill: '2025-07-05',
        url: 'https://www.irctc.co.in/',
      },
      {
        id: '29',
        item: 'Yatra Summer Getaway Deal',
        platform: 'Yatra',
        dealPrice: 6499,
        originalPrice: 6999,
        rating: 4.1,
        validTill: '2025-07-15',
        url: 'https://www.yatra.com/',
      },
      {
        id: '30',
        item: 'Uber 30% Off Airport Rides',
        platform: 'Uber',
        dealPrice: 210,
        originalPrice: 300,
        rating: 4.4,
        validTill: '2025-07-18',
        url: 'https://www.uber.com/in/en/',
      },
      {
        id: '61',
        item: 'Ola Outstation ₹200 Off',
        platform: 'Ola',
        dealPrice: 1800,
        originalPrice: 2000,
        rating: 4.3,
        validTill: '2025-07-20',
        url: 'https://www.olacabs.com/outstation',
      },
      {
        id: '62',
        item: 'Rapido Weekend Discount',
        platform: 'Rapido',
        dealPrice: 60,
        originalPrice: 90,
        rating: 4.0,
        validTill: '2025-07-25',
        url: 'https://www.rapido.bike/',
      },
      {
        id: '63',
        item: 'Cleartrip Hotel Offer ₹300 Off',
        platform: 'Cleartrip',
        dealPrice: 2700,
        originalPrice: 3000,
        rating: 4.1,
        validTill: '2025-08-01',
        url: 'https://www.cleartrip.com/',
      },
      {
        id: '64',
        item: 'Uber Flat ₹40 Off Next Ride',
        platform: 'Uber',
        dealPrice: 60,
        originalPrice: 100,
        rating: 4.4,
        validTill: '2025-08-05',
        url: 'https://www.uber.com/',
      },
      {
        id: '65',
        item: 'Ola Share 50% Off',
        platform: 'Ola',
        dealPrice: 75,
        originalPrice: 150,
        rating: 4.2,
        validTill: '2025-08-10',
        url: 'https://www.olacabs.com/',
      },
      {
        id: '66',
        item: 'RedBus Monsoon Offer',
        platform: 'RedBus',
        dealPrice: 350,
        originalPrice: 450,
        rating: 4.3,
        validTill: '2025-08-15',
        url: 'https://www.redbus.in/',
      },
      {
        id: '67',
        item: 'MakeMyTrip Rail Booking Cashback',
        platform: 'MakeMyTrip',
        dealPrice: 420,
        originalPrice: 500,
        rating: 4.0,
        validTill: '2025-08-20',
        url: 'https://www.makemytrip.com/',
      },
      {
        id: '68',
        item: 'Goibibo Cab Offer ₹100 Off',
        platform: 'Goibibo',
        dealPrice: 150,
        originalPrice: 250,
        rating: 4.1,
        validTill: '2025-08-25',
        url: 'https://www.goibibo.com/',
      },
      {
        id: '69',
        item: 'IRCTC ₹100 Off Tour Package',
        platform: 'IRCTC',
        dealPrice: 1900,
        originalPrice: 2000,
        rating: 4.3,
        validTill: '2025-08-30',
        url: 'https://www.irctctourism.com/',
      },
      {
        id: '70',
        item: 'Yatra Flight Promo ₹500 Cashback',
        platform: 'Yatra',
        dealPrice: 5500,
        originalPrice: 6000,
        rating: 4.2,
        validTill: '2025-09-01',
        url: 'https://www.yatra.com/',
      },
    ],

    Entertainment: [
      {
        id: '31',
        item: 'Hotstar Annual Plan 15% Off',
        platform: 'Hotstar',
        dealPrice: 849,
        originalPrice: 999,
        rating: 4.5,
        validTill: '2025-06-15',
        url: 'https://www.hotstar.com/',
      },
      {
        id: '32',
        item: 'Netflix Basic Plan Deal',
        platform: 'Netflix',
        dealPrice: 149,
        originalPrice: 199,
        rating: 4.6,
        validTill: '2025-06-20',
        url: 'https://www.netflix.com/in/',
      },
      {
        id: '33',
        item: 'Amazon Prime 3-Month Deal',
        platform: 'Amazon Prime',
        dealPrice: 399,
        originalPrice: 499,
        rating: 4.4,
        validTill: '2025-06-30',
        url: 'https://www.primevideo.com/',
      },
      {
        id: '34',
        item: 'Aha Telugu Plan Discount',
        platform: 'Aha',
        dealPrice: 349,
        originalPrice: 399,
        rating: 4.2,
        validTill: '2025-07-01',
        url: 'https://www.aha.video/',
      },
      {
        id: '35',
        item: 'SonyLIV Sports Pack Discount',
        platform: 'SonyLIV',
        dealPrice: 299,
        originalPrice: 399,
        rating: 4.0,
        validTill: '2025-07-05',
        url: 'https://www.sonyliv.com/',
      },
      {
        id: '36',
        item: 'Zee5 Premium Deal ₹499 Yearly',
        platform: 'Zee5',
        dealPrice: 499,
        originalPrice: 699,
        rating: 4.1,
        validTill: '2025-07-10',
        url: 'https://www.zee5.com/',
      },
      {
        id: '37',
        item: 'BookMyShow Buy 1 Get 1 Movie Offer',
        platform: 'BookMyShow',
        dealPrice: 250,
        originalPrice: 500,
        rating: 4.4,
        validTill: '2025-07-15',
        url: 'https://in.bookmyshow.com/',
      },
      {
        id: '38',
        item: 'Voot Premium ₹100 Off',
        platform: 'Voot',
        dealPrice: 299,
        originalPrice: 399,
        rating: 4.0,
        validTill: '2025-07-20',
        url: 'https://www.voot.com/',
      },
      {
        id: '39',
        item: 'Disney+ Monthly Offer ₹149',
        platform: 'Disney+ Hotstar',
        dealPrice: 149,
        originalPrice: 199,
        rating: 4.2,
        validTill: '2025-07-25',
        url: 'https://www.hotstar.com/',
      },
      {
        id: '40',
        item: 'Netflix Mobile Plan at ₹99',
        platform: 'Netflix',
        dealPrice: 99,
        originalPrice: 149,
        rating: 4.6,
        validTill: '2025-08-01',
        url: 'https://www.netflix.com/in/',
      },
      {
        id: '71',
        item: 'Amazon Prime Student Plan ₹499',
        platform: 'Amazon Prime',
        dealPrice: 499,
        originalPrice: 999,
        rating: 4.7,
        validTill: '2025-08-10',
        url: 'https://www.amazon.in/prime',
      },
      {
        id: '72',
        item: 'Spotify Premium ₹129 Monthly',
        platform: 'Spotify',
        dealPrice: 129,
        originalPrice: 199,
        rating: 4.5,
        validTill: '2025-08-15',
        url: 'https://www.spotify.com/in/',
      },
      {
        id: '73',
        item: 'Gaana Plus Annual Offer ₹299',
        platform: 'Gaana',
        dealPrice: 299,
        originalPrice: 499,
        rating: 4.0,
        validTill: '2025-08-18',
        url: 'https://gaana.com/',
      },
      {
        id: '74',
        item: 'JioSaavn Pro ₹399/year',
        platform: 'JioSaavn',
        dealPrice: 399,
        originalPrice: 749,
        rating: 4.3,
        validTill: '2025-08-22',
        url: 'https://www.jiosaavn.com/',
      },
      {
        id: '55',
        item: 'SonyLIV Annual Pack ₹599',
        platform: 'SonyLIV',
        dealPrice: 599,
        originalPrice: 999,
        rating: 4.4,
        validTill: '2025-08-28',
        url: 'https://www.sonyliv.com/',
      },
      {
        id: '76',
        item: 'BookMyShow Stream ₹50 Off',
        platform: 'BookMyShow',
        dealPrice: 149,
        originalPrice: 199,
        rating: 4.1,
        validTill: '2025-09-01',
        url: 'https://in.bookmyshow.com/stream',
      },
      {
        id: '77',
        item: 'Voot Select Monthly Pack ₹99',
        platform: 'Voot',
        dealPrice: 99,
        originalPrice: 149,
        rating: 4.0,
        validTill: '2025-09-05',
        url: 'https://www.voot.com/',
      },
      {
        id: '78',
        item: 'Aha Tamil Annual Plan ₹399',
        platform: 'Aha',
        dealPrice: 399,
        originalPrice: 599,
        rating: 4.2,
        validTill: '2025-09-10',
        url: 'https://www.aha.video/',
      },
      {
        id: '79',
        item: 'Zee5 Weekend Offer ₹50 Cashback',
        platform: 'Zee5',
        dealPrice: 449,
        originalPrice: 499,
        rating: 4.1,
        validTill: '2025-09-12',
        url: 'https://www.zee5.com/',
      },
      {
        id: '80',
        item: 'Hotstar VIP Pack ₹299',
        platform: 'Hotstar',
        dealPrice: 299,
        originalPrice: 399,
        rating: 4.5,
        validTill: '2025-09-15',
        url: 'https://www.hotstar.com/',
      },
    ],
  };

  const categories = Object.keys (dealsByCategory);
  const [selectedCategory, setSelectedCategory] = useState ('All');

  const handleCategoryChange = e => {
    setSelectedCategory (e.target.value);
  };

  const getFilteredDeals = () => {
    if (selectedCategory === 'All') {
      return Object.values (dealsByCategory).flat ();
    } else {
      return dealsByCategory[selectedCategory] || [];
    }
  };

  const filteredDeals = getFilteredDeals ();

  return (
    <div className="best-deal-container">
      <h2>🔥Best Deal Finder</h2>

      <div className="category-filter">
        <label htmlFor="category">Select Category: </label>
        <select
          id="category"
          value={selectedCategory}
          onChange={handleCategoryChange}
        >
          <option value="All">All</option>
          {categories.map (cat => <option key={cat} value={cat}>{cat}</option>)}
        </select>
      </div>

      <div className="deals-grid">
        {filteredDeals.map (deal => (
          <div key={deal.id} className="deal-card">
            <h3>{deal.item}</h3>
            <p><strong>Platform:</strong> {deal.platform}</p>
            <p>
              <strong>Price:</strong>
              {' '}
              ₹
              {deal.dealPrice}
              {' '}
              <span className="original-price">₹{deal.originalPrice}</span>
            </p>
            <p><strong>Rating:</strong> ⭐ {deal.rating}</p>
            <p><strong>Valid Till:</strong> {deal.validTill}</p>
            <a
              href={deal.url}
              target="_blank"
              rel="noopener noreferrer"
              className="visit-link"
            >
              Grab Deal
            </a>
          </div>
        ))}
      </div>
    </div>
  );
};

export default BestDealFinder;
